<a href="https://colab.research.google.com/github/Bishre313/testing/blob/main/AETS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [ ]:
df = pd.read_csv('/content/eVED_181107_week.csv')
df.head()

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Energy_Consumption,Matchted Latitude[deg],Matched Longitude[deg],Match Type,Class of Speed Limit,Speed Limit[km/h],Speed Limit with Direction[km/h],Intersection,Bus Stops,Focus Points
0,372.882455,10.0,3263.0,0.0,42.295477,-83.705005,32.079998,NaN,NaN,NaN,...,0.004811,42.295487,-83.704927,0,0.0,64,64.0,NaN,NaN,NaN
1,372.882455,10.0,3263.0,900.0,42.295477,-83.705005,35.730000,NaN,NaN,NaN,...,0.004811,42.295487,-83.704927,1,0.0,64,64.0,NaN,NaN,NaN
2,372.882455,10.0,3263.0,1100.0,42.295477,-83.705005,35.730000,NaN,NaN,NaN,...,0.005334,42.295487,-83.704927,1,0.0,64,64.0,NaN,NaN,NaN
3,372.882455,10.0,3263.0,2000.0,42.295477,-83.705005,38.770000,NaN,NaN,NaN,...,0.005334,42.295487,-83.704927,1,0.0,64,64.0,NaN,NaN,NaN
4,372.882455,10.0,3263.0,2100.0,42.295477,-83.705005,38.770000,NaN,NaN,NaN,...,0.005857,42.295487,-83.704927,1,0.0,64,64.0,NaN,NaN,NaN

EDA

In [ ]:
df.describe()

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Elevation Smoothed[m],Gradient,Energy_Consumption,Matchted Latitude[deg],Matched Longitude[deg],Match Type,Class of Speed Limit,Speed Limit with Direction[km/h],Intersection,Bus Stops
count,118327.000000,118327.000000,118327.000000,1.183270e+05,118327.000000,118327.000000,118327.000000,97031.000000,115831.000000,94621.000000,...,118327.000000,1.158410e+05,72385.000000,118327.000000,118327.000000,118327.000000,114830.000000,114830.000000,4918.0,2064.0
mean,373.513352,396.167527,2639.658134,4.279688e+05,42.274079,-83.727706,40.730260,8.649900,1072.953708,28.402252,...,261.172327,7.900452e-07,0.002564,42.274074,-83.727713,0.841177,0.163424,57.481503,1.0,1.0
std,0.787754,143.513443,1507.086975,4.089854e+05,0.021140,0.031492,26.436418,9.816217,797.872239,20.867471,...,16.371560,3.018066e-03,0.003992,0.021138,0.031493,0.396819,0.411023,16.580288,0.0,0.0
min,372.021352,10.000000,561.000000,0.000000e+00,42.223557,-83.802061,0.000000,0.000000,0.000000,0.000000,...,227.392990,-9.845107e-02,-0.014826,42.223671,-83.802060,0.000000,-1.000000,16.000000,1.0,1.0
25%,372.867451,283.000000,1853.000000,1.239000e+05,42.257859,-83.749405,21.000000,1.560000,0.000000,12.941176,...,249.193614,0.000000e+00,0.000076,42.257864,-83.749382,1.000000,0.000000,48.000000,1.0,1.0
50%,373.556549,450.000000,2336.000000,3.000000e+05,42.277726,-83.731034,43.000000,4.130000,1174.000000,23.137255,...,258.944305,0.000000e+00,0.001174,42.277724,-83.731061,1.000000,0.000000,56.000000,1.0,1.0
75%,373.879549,492.000000,2998.000000,6.009000e+05,42.287449,-83.700188,58.000000,13.450000,1596.000000,45.882355,...,274.065930,0.000000e+00,0.004150,42.287488,-83.700155,1.000000,0.000000,64.000000,1.0,1.0
max,375.501195,610.000000,11580.000000,1.973500e+06,42.324148,-83.674018,135.000000,107.089996,4295.000000,175.686279,...,321.704376,1.122136e-01,0.071605,42.324178,-83.673920,2.000000,2.000000,113.000000,1.0,1.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118327 entries, 0 to 118326
Data columns (total 35 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   DayNum                            118327 non-null  float64
 1   VehId                             118327 non-null  float64
 2   Trip                              118327 non-null  float64
 3   Timestamp(ms)                     118327 non-null  float64
 4   Latitude[deg]                     118327 non-null  float64
 5   Longitude[deg]                    118327 non-null  float64
 6   Vehicle Speed[km/h]               118327 non-null  float64
 7   MAF[g/sec]                        97031 non-null   float64
 8   Engine RPM[RPM]                   115831 non-null  float64
 9   Absolute Load[%]                  94621 non-null   float64
 10  OAT[DegC]                         94605 non-null   float64
 11  Fuel Rate[L/hr]                   6454 non-null    float64
 12  Air Conditioning Power[kW]        6454 non-null    float64
 13  Air Conditioning Power[Watts]     13221 non-null   float64
 14  Heater Power[Watts]               8950 non-null    float64
 15  HV Battery Current[A]             19675 non-null   float64
 16  HV Battery SOC[%]                 19675 non-null   float64
 17  HV Battery Voltage[V]             19675 non-null   float64
 18  Short Term Fuel Trim Bank 1[%]    78250 non-null   float64
 19  Short Term Fuel Trim Bank 2[%]    27779 non-null   float64
 20  Long Term Fuel Trim Bank 1[%]     60874 non-null   float64
 21  Long Term Fuel Trim Bank 2[%]     10553 non-null   float64
 22  Elevation Raw[m]                  118327 non-null  float64
 23  Elevation Smoothed[m]             118327 non-null  float64
 24  Gradient                          115841 non-null  float64
 25  Energy_Consumption                72385 non-null   float64
 26  Matchted Latitude[deg]            118327 non-null  float64
 27  Matched Longitude[deg]            118327 non-null  float64
 28  Match Type                        118327 non-null  int64
 29  Class of Speed Limit              114830 non-null  float64
 30  Speed Limit[km/h]                 114830 non-null  object
 31  Speed Limit with Direction[km/h]  114830 non-null  float64
 32  Intersection                      4918 non-null    float64
 33  Bus Stops                         2064 non-null    float64
 34  Focus Points                      2931 non-null    object
dtypes: float64(32), int64(1), object(2)
memory usage: 31.6+ MB

In [ ]:
df.shape

(118327, 35)

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Bus Stops                           116263
Focus Points                        115396
Intersection                        113409
Fuel Rate[L/hr]                     111873
Air Conditioning Power[kW]          111873
Heater Power[Watts]                 109377
Long Term Fuel Trim Bank 2[%]       107774
Air Conditioning Power[Watts]       105106
HV Battery SOC[%]                    98652
HV Battery Current[A]                98652
HV Battery Voltage[V]                98652
Short Term Fuel Trim Bank 2[%]       90548
Long Term Fuel Trim Bank 1[%]        57453
Energy_Consumption                   45942
Short Term Fuel Trim Bank 1[%]       40077
OAT[DegC]                            23722
Absolute Load[%]                     23706
MAF[g/sec]                           21296
Class of Speed Limit                  3497
Speed Limit with Direction[km/h]      3497
Speed Limit[km/h]                     3497
Engine RPM[RPM]                       2496
Gradient                              2486
Trip                                     0
VehId                                    0
DayNum                                   0
Timestamp(ms)                            0
Vehicle Speed[km/h]                      0
Longitude[deg]                           0
Latitude[deg]                            0
Elevation Raw[m]                         0
Matchted Latitude[deg]                   0
Elevation Smoothed[m]                    0
Matched Longitude[deg]                   0
Match Type                               0
dtype: int64

In [ ]:
df.describe()

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Elevation Smoothed[m],Gradient,Energy_Consumption,Matchted Latitude[deg],Matched Longitude[deg],Match Type,Class of Speed Limit,Speed Limit with Direction[km/h],Intersection,Bus Stops
count,118327.000000,118327.000000,118327.000000,1.183270e+05,118327.000000,118327.000000,118327.000000,97031.000000,115831.000000,94621.000000,...,118327.000000,1.158410e+05,72385.000000,118327.000000,118327.000000,118327.000000,114830.000000,114830.000000,4918.0,2064.0
mean,373.513352,396.167527,2639.658134,4.279688e+05,42.274079,-83.727706,40.730260,8.649900,1072.953708,28.402252,...,261.172327,7.900452e-07,0.002564,42.274074,-83.727713,0.841177,0.163424,57.481503,1.0,1.0
std,0.787754,143.513443,1507.086975,4.089854e+05,0.021140,0.031492,26.436418,9.816217,797.872239,20.867471,...,16.371560,3.018066e-03,0.003992,0.021138,0.031493,0.396819,0.411023,16.580288,0.0,0.0
min,372.021352,10.000000,561.000000,0.000000e+00,42.223557,-83.802061,0.000000,0.000000,0.000000,0.000000,...,227.392990,-9.845107e-02,-0.014826,42.223671,-83.802060,0.000000,-1.000000,16.000000,1.0,1.0
25%,372.867451,283.000000,1853.000000,1.239000e+05,42.257859,-83.749405,21.000000,1.560000,0.000000,12.941176,...,249.193614,0.000000e+00,0.000076,42.257864,-83.749382,1.000000,0.000000,48.000000,1.0,1.0
50%,373.556549,450.000000,2336.000000,3.000000e+05,42.277726,-83.731034,43.000000,4.130000,1174.000000,23.137255,...,258.944305,0.000000e+00,0.001174,42.277724,-83.731061,1.000000,0.000000,56.000000,1.0,1.0
75%,373.879549,492.000000,2998.000000,6.009000e+05,42.287449,-83.700188,58.000000,13.450000,1596.000000,45.882355,...,274.065930,0.000000e+00,0.004150,42.287488,-83.700155,1.000000,0.000000,64.000000,1.0,1.0
max,375.501195,610.000000,11580.000000,1.973500e+06,42.324148,-83.674018,135.000000,107.089996,4295.000000,175.686279,...,321.704376,1.122136e-01,0.071605,42.324178,-83.673920,2.000000,2.000000,113.000000,1.0,1.0

In [ ]:
for col in df.columns:
    print(repr(col))

'DayNum'
'VehId'
'Trip'
'Timestamp(ms)'
'Latitude[deg]'
'Longitude[deg]'
'Vehicle Speed[km/h]'
'MAF[g/sec]'
'Engine RPM[RPM]'
'Absolute Load[%]'
'OAT[DegC]'
'Fuel Rate[L/hr]'
'Air Conditioning Power[kW]'
'Air Conditioning Power[Watts]'
'Heater Power[Watts]'
'HV Battery Current[A]'
'HV Battery SOC[%]'
'HV Battery Voltage[V]'
'Short Term Fuel Trim Bank 1[%]'
'Short Term Fuel Trim Bank 2[%]'
'Long Term Fuel Trim Bank 1[%]'
'Long Term Fuel Trim Bank 2[%]'
'Elevation Raw[m]'
'Elevation Smoothed[m]'
'Gradient'
'Energy_Consumption'
'Matchted Latitude[deg]'
'Matched Longitude[deg]'
'Match Type'
'Class of Speed Limit'
'Speed Limit[km/h]'
'Speed Limit with Direction[km/h]'
'Intersection'
'Bus Stops'
'Focus Points'

In [ ]:
# Convert only the problematic column to numeric
df['Speed Limit[km/h]'] = pd.to_numeric(df['Speed Limit[km/h]'], errors='coerce')

# Now fill missing values
df['Speed Limit[km/h]'].fillna(df['Speed Limit[km/h]'].median(), inplace=True)

# This column is already numeric, just fill
df['Speed Limit with Direction[km/h]'].fillna(
    df['Speed Limit with Direction[km/h]'].median(), inplace=True
)

/tmp/ipython-input-3617029715.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Speed Limit[km/h]'].fillna(df['Speed Limit[km/h]'].median(), inplace=True)
/tmp/ipython-input-3617029715.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Speed Limit with Direction[km/h]'].fillna(

In [ ]:
print(df['Speed Limit[km/h]'].dtype)
print(df['Speed Limit with Direction[km/h]'].isnull().sum())

float64
0

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Bus Stops                           116263
Focus Points                        115396
Intersection                        113409
Fuel Rate[L/hr]                     111873
Air Conditioning Power[kW]          111873
Heater Power[Watts]                 109377
Long Term Fuel Trim Bank 2[%]       107774
Air Conditioning Power[Watts]       105106
HV Battery SOC[%]                    98652
HV Battery Current[A]                98652
HV Battery Voltage[V]                98652
Short Term Fuel Trim Bank 2[%]       90548
Long Term Fuel Trim Bank 1[%]        57453
Energy_Consumption                   45942
Short Term Fuel Trim Bank 1[%]       40077
OAT[DegC]                            23722
Absolute Load[%]                     23706
MAF[g/sec]                           21296
Class of Speed Limit                  3497
Engine RPM[RPM]                       2496
Gradient                              2486
DayNum                                   0
VehId                                    0
Trip                                     0
Longitude[deg]                           0
Latitude[deg]                            0
Timestamp(ms)                            0
Vehicle Speed[km/h]                      0
Matchted Latitude[deg]                   0
Elevation Raw[m]                         0
Elevation Smoothed[m]                    0
Speed Limit[km/h]                        0
Match Type                               0
Matched Longitude[deg]                   0
Speed Limit with Direction[km/h]         0
dtype: int64

In [ ]:
target = 'Energy_Consumption'

threshold = 0.7 * len(df)

high_missing_cols = df.isnull().sum()[
    (df.isnull().sum() > threshold) & (df.columns != target)
].index

df.drop(columns=high_missing_cols, inplace=True)

print("Dropped Columns:", list(high_missing_cols))
print("Target still present:", target in df.columns)

Dropped Columns: ['Fuel Rate[L/hr]', 'Air Conditioning Power[kW]', 'Air Conditioning Power[Watts]', 'Heater Power[Watts]', 'HV Battery Current[A]', 'HV Battery SOC[%]', 'HV Battery Voltage[V]', 'Short Term Fuel Trim Bank 2[%]', 'Long Term Fuel Trim Bank 2[%]', 'Intersection', 'Bus Stops', 'Focus Points']
Target still present: True

In [ ]:
# Step 2: Interpolate medium-missing time-series features
medium_missing_cols = [
    'Energy_Consumption',
    'Absolute Load[%]',
    'MAF[g/sec]'
]

for col in medium_missing_cols:
    if col in df.columns:
        df[col] = df[col].interpolate(method='linear')

In [ ]:
# Step 3: Handle low-missing values
df['Gradient'] = df['Gradient'].interpolate(method='linear')
df['Engine RPM[RPM]'] = df['Engine RPM[RPM]'].interpolate(method='linear')
df['Vehicle Speed[km/h]'] = df['Vehicle Speed[km/h]'].interpolate(method='linear')

# Categorical → fill with mode
df['Class of Speed Limit'].fillna(df['Class of Speed Limit'].mode()[0], inplace=True)

/tmp/ipython-input-208176911.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Class of Speed Limit'].fillna(df['Class of Speed Limit'].mode()[0], inplace=True)

In [ ]:
# Fill any remaining numeric NaNs with median
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

print("Remaining Missing Values:\n", df.isnull().sum().sum())

Remaining Missing Values:
 0

In [ ]:
df.isnull().sum().sort_values(ascending=False)

DayNum                              0
VehId                               0
Trip                                0
Timestamp(ms)                       0
Latitude[deg]                       0
Longitude[deg]                      0
Vehicle Speed[km/h]                 0
MAF[g/sec]                          0
Engine RPM[RPM]                     0
Absolute Load[%]                    0
Elevation Raw[m]                    0
Elevation Smoothed[m]               0
Gradient                            0
Energy_Consumption                  0
Matchted Latitude[deg]              0
Matched Longitude[deg]              0
Match Type                          0
Class of Speed Limit                0
Speed Limit[km/h]                   0
Speed Limit with Direction[km/h]    0
dtype: int64

In [ ]:
# If Timestamp exists, use it
if 'Timestamp(ms)' in df.columns:
    df['Timestamp'] = pd.to_datetime(df['Timestamp(ms)'], unit='ms')
    df['Hour'] = df['Timestamp'].dt.hour
    df['Day'] = df['Timestamp'].dt.day

In [ ]:
df['Speed_x_RPM'] = df['Vehicle Speed[km/h]'] * df['Engine RPM[RPM]']
df['Elevation_Change'] = df['Elevation Smoothed[m]'].diff().fillna(0)

ENCODE

In [ ]:
le = LabelEncoder()

if 'Class of Speed Limit' in df.columns:
    df['Class of Speed Limit'] = le.fit_transform(df['Class of Speed Limit'])

if 'Match Type' in df.columns:
    df['Match Type'] = le.fit_transform(df['Match Type'])

In [ ]:
#drop leaking colmns
drop_cols = [
    'VehId', 'Trip',
    'Matchted Latitude[deg]', 'Matched Longitude[deg]',
    'Timestamp(ms)', 'Timestamp'
]
df = df.drop(columns=drop_cols, errors='ignore')

# Remove invalid/zero/negative energy values
df = df[df['Energy_Consumption'] > 0]

# Clip extreme outliers (1% to 99%)
q_low = df['Energy_Consumption'].quantile(0.01)
q_high = df['Energy_Consumption'].quantile(0.99)
df['Energy_Consumption'] = df['Energy_Consumption'].clip(q_low, q_high)

# Log transform target to stabilize tiny values
df['Energy_Consumption'] = np.log1p(df['Energy_Consumption'])


X = df.drop(columns=['Energy_Consumption'])
y = df['Energy_Consumption']

In [ ]:
print('Energy_Consumption' in df.columns)
print(df.columns.tolist())

True
['DayNum', 'Latitude[deg]', 'Longitude[deg]', 'Vehicle Speed[km/h]', 'MAF[g/sec]', 'Engine RPM[RPM]', 'Absolute Load[%]', 'Elevation Raw[m]', 'Elevation Smoothed[m]', 'Gradient', 'Energy_Consumption', 'Match Type', 'Class of Speed Limit', 'Speed Limit[km/h]', 'Speed Limit with Direction[km/h]', 'Hour', 'Day', 'Speed_x_RPM', 'Elevation_Change']

In [ ]:
target = 'Energy_Consumption'

X = df.drop(columns=[target])
y = df[target]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (426461, 18)
Target shape: (426461,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

In [ ]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 0.0020106288213040404
R2 Score: -0.34969152181739616

In [ ]:
print("Target stats:")
print(y.describe())
print("\nZero values:", (y == 0).sum())
print("Unique values:", y.nunique())

Target stats:
count    426461.000000
mean          0.003199
std           0.003011
min           0.000024
25%           0.000900
50%           0.002283
75%           0.004650
max           0.012694
Name: Energy_Consumption, dtype: float64

Zero values: 0
Unique values: 379295